name: flutter_audio_visualizer_example
description: Example app for the flutter_audio_visualizer package.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_audio_visualizer:
    path: ../

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
